### PR TITLE
Configure networking for Softlayer VM

### PR DESCRIPTION
**Pull request by jianqiu**
In order to keep persistent with the networking setting in legacy cpi,  eCPI should append powerdns ip into the dns list of vm. So `bosh_ip` should be indicated in the cloud properties section in deployment yml before deploying.

### CODE REVIEW

**Comment by maximilien** [comment]
Please fix the conflicts and I will check and merge, thanks.

configure_networking_for_softlayer_vm_by_jianqiu_ _pull_request__62_ _maximilien_bosh-softlayer-cpi

**Comment by jianqiu** [comment]
@maximilien 
The conflicts had been resolved, please review them,thanks!

**Comment by maximilien** [comment]
@jianqiu, one more thing, can you please rebase to remove the Godeps changes since these are already updated on master. I will review ASAP and comment or merge.

Sorry about that. Thanks.

**Comment by jianqiu** [comment]
@maximilien 
I just submitted a new PR in softlayer-go (https://github.com/maximilien/softlayer-go/pull/49), if it could be merged, could you please update godep workspace in CPI again? Then, I can rebase  and remove the godep changes included in PR of softlayer-go, thanks!

**Comment by maximilien** [comment]
@jianqiu, 

Yes will update Godeps if the PR is merged. However, I think the code in PR belongs to this project. See comments there. Once we agree on where to put code then we can revisit this Godeps update (if needed). Best,

@maximilien

**Comment by maximilien** [comment]
Hi, @jianqui,

Do you want to reuse this PR to submit code we updated today or should I close this?

Best,

Max

**Comment by maximilien** [comment]
Closing this as per today's discussion, please resubmit.

**Pull request closed without merging**
