### PR TITLE
Updated integration tests to use DATACENTER constant in softlayer-go

### PR DESCRIPTION
**Pull request by karafelix**
Aside from the issue of that this works presently, I'm starting to wonder, after wading through trying to update godeps, if it might be better to pull the datacenter from an environment variable?
As it is, if we want to change the datacenter, it's only in a constant in softlayer-go, but this has its own copy of softlayer-go, and the actual source would have to be changed.

### CODE REVIEW

**Comment by maximilien** [comment]
We typically separate the Godeps updates into it's own PR. Please do that.

Also, why not do the work for changing to env variable and update this PR. That way I will review two PRs (Godeps) and this one and merge them. Coo?

**Comment by karafelix** [comment]
I couldn't manage to figure out how to update the Godeps, aside from changing it manually.
I'll update this one to use an env variable though.

**Comment by karafelix** [comment]
Updated to check environment variable now.

**Comment by karafelix** [comment]
Ohhhh, I must have accidentally started from jianqiu's branch, that's what there's so much in here more than just what I changed.

Closing this request and going to try to figure out how to redo this for just my changes, then I'll submit another PR.

**Comment by karafelix** [comment]
Oh, upon further reflection, it looks like I had merged in the changes you accepted in master into the stemcell_integration branch. Hrm.
I'm going to start fresh from your current stemcell_integration branch, to make the changes to just that; once we merge that in, we should merge the stemcell_integration branch into master.

**Pull request closed without merging**
