### PR TITLE
vm delete - fix two problems

### PR DESCRIPTION
**Pull request by gu-bin**
1. fix bug when transaction average duration begins with "."
2. if vm id is invalid, just exit delete_vm and don't return err

### CODE REVIEW

**Comment by gu-bin** [comment]
There is problems with create vm tests. So the travis-ci can't pass.

**Comment by maximilien** [comment]
This is not passing Travis. Might need to rebase @gu-bin

**Comment by gu-bin** [comment]
Travis passed

**Comment by gu-bin** [comment]
@maximilien would you please view and merge this one? Thanks.

**Comment by maximilien** [comment]
OK cool. I hope however, we are not depending on this `averageDuration` value for serious business?

**Pull request merged**
