### PR TITLE
changed several broken links to dependencies, cleaned up godep

### PR DESCRIPTION
**Pull request by posijon**

### CODE REVIEW

**Comment by maximilien** [comment]
Let's make sure to wait for Travis to go green before merging. Cool to getting this fixed. Cheers :beers:

**Comment by posijon** [comment]
I'm actually having trouble finding one of the dependencies required for unit testing.

**Comment by maximilien** [comment]
Can you email or post what the issue is?

**Comment by maximilien** [comment]
From Travis it seems that: `github.com/cloudfoundry/bosh-agent/platform/commands/fakes` is not being found so need to `go get` and Godeps save it?

**Comment by maximilien** [comment]
Seems that this worked now on Travis, so I am merging. Cheers.

**Pull request merged**
